// AUTO-GENERATED by scripts/set-env.js — do not edit directly.
export const environment = {
  production: false,
  supabaseUrl: 'https://hlkczvkpdmcgchlawnnt.supabase.co',
  supabaseAnonKey: 'sb_publishable_1mkfsqk51WYAyllm8L4wYg_sBcCKynW',
};
