// AUTO-GENERATED by scripts/set-env.js — do not edit directly.
export const environment = {
  production: true,
  supabaseUrl: 'https://ddvudvwmksjxrmocpyqv.supabase.co',
  supabaseAnonKey: 'sb_publishable_TCxMtglGShxWTstUecKpbQ_PjTc_mV7',
};
