// Generates src/environments/environment.ts and environment.prod.ts from
// environment variables at build time. This is what lets Cloudflare Pages
// (a static host with no server-side runtime) inject secrets into an
// Angular build: set NG_APP_SUPABASE_URL and NG_APP_SUPABASE_ANON_KEY in the
// Cloudflare Pages dashboard under Settings > Environment variables, and this
// script bakes them into the compiled JS at build time.
const fs = require('fs');
const path = require('path');

const supabaseUrl = process.env.NG_APP_SUPABASE_URL || '';
const supabaseAnonKey = process.env.NG_APP_SUPABASE_ANON_KEY || '';

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn(
    '[set-env] NG_APP_SUPABASE_URL / NG_APP_SUPABASE_ANON_KEY not set — ' +
    'keeping existing values in src/environments/*.ts (fine for local dev).'
  );
  process.exit(0);
}

const template = (production) => `// AUTO-GENERATED by scripts/set-env.js — do not edit directly.
export const environment = {
  production: ${production},
  supabaseUrl: '${supabaseUrl}',
  supabaseAnonKey: '${supabaseAnonKey}',
};
`;

const envDir = path.join(__dirname, '..', 'src', 'environments');
fs.writeFileSync(path.join(envDir, 'environment.ts'), template(false));
fs.writeFileSync(path.join(envDir, 'environment.prod.ts'), template(true));

console.log('[set-env] Wrote environment files from process.env.');
